#!/usr/bin/env bash
# Example deploy script — generated by configure.py (do not edit manually).
# cfn-deploy.sh is gitignored so your API key is never committed.
#
# Recommended path: run 'python3 configure.py' — it handles everything:
#   1. Creates the Lambda deployment bucket automatically
#   2. Builds and uploads the Lambda code
#   3. Deploys this CloudFormation stack
#
# Manual path (advanced):
#   1. Create an S3 bucket to hold the Lambda package
#   2. Run ./build.sh --bucket <bucket-name> to upload the code
#   3. Fill in LambdaDeployBucketName below and run this script

set -euo pipefail

aws cloudformation deploy \
  --template-file template.yaml \
  --stack-name ai-guard-monitor \
  --region "us-east-1" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --parameter-overrides \
    LambdaDeployBucketName="my-ai-guard-deploy-bucket" \
    AIGuardApiKey="YOUR_VISION_ONE_API_KEY" \
    AIGuardEndpoint="https://api.xdr.trendmicro.com/v3.0/xdr/guard/scan" \
    AIGuardAppName="ai-guard-s3-monitor" \
    SourceBucketName="my-existing-source-bucket" \
    LogBucketName="my-ai-guard-logs" \
    NotificationEmail="" \
    SESVerifiedSender="" \
    MaxTextKB="500" \
    LambdaMemoryMB="512" \
    LambdaTimeoutSeconds="300" \
    LogRetentionDays="90" \
    EnableCloudWatchMonitoring="No"

echo "Stack deployed. Check Outputs tab in CloudFormation for next steps."
