#!/usr/bin/env bash
# Example of the cfn-deploy.sh generated by install.sh (do not run directly).
# cfn-deploy.sh is gitignored so your API key is never committed.
#
# The real cfn-deploy.sh generated by install.sh is self-sufficient:
#   1. Creates the Lambda deployment bucket if it does not exist
#   2. Builds and uploads the Lambda package from src/
#   3. Removes any orphaned CloudWatch log groups from a previous deployment
#   4. Deploys (or updates) the CloudFormation stack
#
# This means you can safely run cfn-deploy.sh after an uninstall, on a new
# machine, or any time without running install.sh again.
#
# To regenerate cfn-deploy.sh (e.g. after changing config), re-run install.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Configuration (filled in by install.sh) ───────────────────────────────────
STACK_NAME="ai-guard-monitor"
REGION="us-east-1"
ACCOUNT_ID="YOUR_AWS_ACCOUNT_ID"
DEPLOY_BUCKET="${STACK_NAME}-deploy-${ACCOUNT_ID}"
LAMBDA_S3_KEY="lambda/package.zip"
API_KEY="YOUR_VISION_ONE_API_KEY"
ENDPOINT="https://api.xdr.trendmicro.com/v3.0/aiSecurity/applyGuardrails"
APP_NAME="ai-guard-s3-monitor"
SOURCE_BUCKET="my-existing-source-bucket"
LOG_BUCKET="my-ai-guard-logs"
NOTIFICATION_EMAIL=""
SES_SENDER=""
MAX_TEXT_KB="50"
LAMBDA_MEMORY="512"
LAMBDA_TIMEOUT="300"
LOG_RETENTION="90"
ENABLE_TAGGING="No"
ENABLE_CW="No"

# ── 1. Deploy bucket ──────────────────────────────────────────────────────────
echo "==> Checking Lambda deploy bucket: ${DEPLOY_BUCKET}"
if ! aws s3api head-bucket --bucket "${DEPLOY_BUCKET}" --region "${REGION}" >/dev/null 2>&1; then
    echo "    Creating ${DEPLOY_BUCKET}..."
    if [[ "${REGION}" == "us-east-1" ]]; then
        aws s3api create-bucket --bucket "${DEPLOY_BUCKET}" --region "${REGION}" >/dev/null
    else
        aws s3api create-bucket --bucket "${DEPLOY_BUCKET}" --region "${REGION}" \
            --create-bucket-configuration LocationConstraint="${REGION}" >/dev/null
    fi
    aws s3api put-public-access-block --bucket "${DEPLOY_BUCKET}" \
        --public-access-block-configuration \
        "BlockPublicAcls=true,BlockPublicPolicy=true,IgnorePublicAcls=true,RestrictPublicBuckets=true" >/dev/null
    aws s3api put-bucket-encryption --bucket "${DEPLOY_BUCKET}" \
        --server-side-encryption-configuration \
        '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}' >/dev/null
    echo "    Created."
else
    echo "    Already exists."
fi

# ── 2. Build and upload Lambda package ───────────────────────────────────────
echo "==> Building Lambda package..."
BUILD_DIR=$(mktemp -d)
ZIP_FILE=$(mktemp).zip
trap 'rm -rf "${BUILD_DIR}" "${ZIP_FILE}" 2>/dev/null || true' EXIT

pip3 install -r "${SCRIPT_DIR}/src/requirements.txt" \
    -t "${BUILD_DIR}" \
    --platform manylinux2014_x86_64 \
    --only-binary=:all: \
    --python-version 3.12 \
    --implementation cp \
    --upgrade \
    -q

cp "${SCRIPT_DIR}/src/"*.py "${BUILD_DIR}/"
( cd "${BUILD_DIR}" && zip -rq "${ZIP_FILE}" . )

echo "==> Uploading to s3://${DEPLOY_BUCKET}/${LAMBDA_S3_KEY} ..."
aws s3 cp "${ZIP_FILE}" "s3://${DEPLOY_BUCKET}/${LAMBDA_S3_KEY}" --region "${REGION}"
echo "    Uploaded."

# ── 3. Pre-flight: remove orphaned log groups ─────────────────────────────────
ORPHANS=$(aws logs describe-log-groups --region "${REGION}" \
    --log-group-name-prefix "/aws/lambda/${STACK_NAME}-" \
    --query 'logGroups[].logGroupName' --output text 2>/dev/null || true)
if [[ -n "${ORPHANS}" ]]; then
    echo "==> Removing orphaned log groups from previous deployment..."
    for lg in ${ORPHANS}; do
        aws logs delete-log-group --log-group-name "${lg}" --region "${REGION}"
        echo "    Removed: ${lg}"
    done
fi

# ── 4. Deploy CloudFormation stack ───────────────────────────────────────────
echo "==> Deploying CloudFormation stack: ${STACK_NAME}"
aws cloudformation deploy \
  --template-file "${SCRIPT_DIR}/template.yaml" \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
    AIGuardApiKey="${API_KEY}" \
    AIGuardEndpoint="${ENDPOINT}" \
    AIGuardAppName="${APP_NAME}" \
    SourceBucketName="${SOURCE_BUCKET}" \
    LogBucketName="${LOG_BUCKET}" \
    NotificationEmail="${NOTIFICATION_EMAIL}" \
    SESVerifiedSender="${SES_SENDER}" \
    MaxTextKB="${MAX_TEXT_KB}" \
    LambdaMemoryMB="${LAMBDA_MEMORY}" \
    LambdaTimeoutSeconds="${LAMBDA_TIMEOUT}" \
    LogRetentionDays="${LOG_RETENTION}" \
    EnableFileTagging="${ENABLE_TAGGING}" \
    EnableCloudWatchMonitoring="${ENABLE_CW}"

echo ""
echo "Stack deployed successfully."
