#!/usr/bin/env bash
# Example deploy script — generated by configure.py (do not edit manually).
# cfn-deploy.sh is gitignored so your API key is never committed.
#
# NOTE: The Lambda deployment bucket is created automatically by the stack.
#       Run ./build.sh <stack-name> AFTER the first deploy to upload code,
#       then re-run this script to activate the scanner Lambda.
#
# Simplest path: run 'python3 configure.py' — it handles everything in order.

set -euo pipefail

aws cloudformation deploy \
  --template-file template.yaml \
  --stack-name ai-guard-monitor \
  --region "us-east-1" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --parameter-overrides \
    LambdaCodeS3Key="ai-guard-monitor/lambda-20240101-120000.zip" \
    AIGuardApiKey="YOUR_VISION_ONE_API_KEY" \
    AIGuardEndpoint="https://api.xdr.trendmicro.com/v3.0/xdr/guard/scan" \
    AIGuardAppName="ai-guard-s3-monitor" \
    SourceBucketName="my-existing-source-bucket" \
    LogBucketName="my-ai-guard-logs" \
    NotificationEmail="" \
    SESVerifiedSender="" \
    MaxTextKB="500" \
    LambdaMemoryMB="512" \
    LambdaTimeoutSeconds="300" \
    LogRetentionDays="90" \
    EnableCloudWatchMonitoring="No"

echo "Stack deployed. Check Outputs tab in CloudFormation for next steps."
